### PR TITLE
Updated page for new localizer onboarding

### PR DESCRIPTION
**Pull request by Delphine**

### CODE REVIEW

**Comment by Delphine** [comment]
I just realized I made a bunch of errors that I need to fix - will address tomorrow (lots of links to update)

**Comment by flodolo** [comment]
> I just realized I made a bunch of errors that I need to fix - will address tomorrow (lots of links to update)

Not sure you can fix the link without having all the code running locally. I'll give it a pass, and let you fix the rest of the content if needed.

**Comment by flodolo** [comment]
Actually, I only found one incorrect link, all the others are working as expected.

This is how the page currently looks like.

Screenshot 2024-06-27 at 07-20-45 Localization at Mozilla Introduction to Mozilla Localization

**Review by flodolo — APPROVED** [review]
You can see the changes I made here. If you don't have any follow-up, feel free to merge.
https://github.com/mozilla-l10n/introduction/pull/3/commits/cec07d6119a62c38d9e71acf9a1098fdbfcc1e29

**Review by peiying2 — APPROVED** [review]
additional change (adding links) looks good!

**Pull request merged**
